#!/usr/bin/expect

spawn bash gencert.sh

expect "key:" {send "12345\r"} 
expect "key:" {send "12345\r"} 
expect "key:" {send "12345\r"} 
expect "key:" {send "12345\r"} 
expect "key:" {send "12345\r"} 


